cdr_gan_dmf_param_ssl_al_pid_sweep:
  yml:cdr_gan_dmf_param_ssl_al_pid_sweep.yml
method: grid
metric:
  name: test_hr_t
  goal: maximize
parameters:
  noise_multiplier_:
    values:
      [0.1, 1, 10, 126, 256, 512, 1000] #0.1,1, 10,126, 512, 1000

  model_config:
    value:

  lr_t:
    values:
      [0.02, 0.03, 0.05]

  lr_d:
    values:
      [0.0001]
  lr_g:
    values:
      [ 0.0001, 0.00005 ]

#  uuid_tag:
#    value:
#      test_model_s_swp_noise_dp_compute